exception E;
fun f _ = () handle E => ();
