exception E;
val x = E;
